import { Operation } from "@tellescope/types-utilities";
import { AccessAction, AccessForResource, AccessPermissions, AccessType, Enduser, EnduserRelationship, FormFieldType, InsuranceRelationship, TellescopeGender } from "@tellescope/types-models";
export type EnduserField = keyof Pick<Enduser, 'email' | 'phone' | 'fname' | 'lname' | 'dateOfBirth' | 'height' | 'weight'>;
export declare const ALL_ENDUSER_FIELDS_TO_DISPLAY_NAME: {
    id: string;
    assignedTo: string;
    fname: string;
    lname: string;
    email: string;
    phone: string;
    dateOfBirth: string;
    height: string;
    weight: string;
    gender: string;
    tags: string;
    journeys: string;
    addressLineOne: string;
    addressLineTwo: string;
    city: string;
    state: string;
    zipCode: string;
    landline: string;
    timezone: string;
    mname: string;
    externalId: string;
    source: string;
    relationships: string;
    accessTags: string;
    unsubscribedFromMarketing: string;
    unsubscribedFromPhones: string;
    athenaDepartmentId: string;
    termsVersion: string;
    customTypeId: string;
};
export declare const ENDUSER_FIELDS_WITH_NESTED_PATHS_DISPLAY_NAME: {
    readonly 'insurance.payerName': "Insurance Primary - Payer Name";
    readonly 'insurance.memberId': "Insurance Primary - Member ID";
    readonly 'insurance.payerId': "Insurance Primary - Payer ID";
    readonly 'insurance.groupNumber': "Insurance Primary - Group Number";
    readonly 'insurance.planName': "Insurance Primary - Plan Name";
    readonly 'insurance.relationship': "Insurance Primary - Relationship";
    readonly 'insurance.eligibility': "Insurance Primary - Eligibility";
    readonly 'insurance.status': "Insurance Primary - Status";
    readonly 'insurance.payerType': "Insurance Primary - Payer Type";
    readonly 'insurance.startDate': "Insurance Primary - Start Date";
    readonly 'insuranceSecondary.payerName': "Insurance Secondary - Payer Name";
    readonly 'insuranceSecondary.memberId': "Insurance Secondary - Member ID";
    readonly 'insuranceSecondary.payerId': "Insurance Secondary - Payer ID";
    readonly 'insuranceSecondary.groupNumber': "Insurance Secondary - Group Number";
    readonly 'insuranceSecondary.planName': "Insurance Secondary - Plan Name";
    readonly 'insuranceSecondary.relationship': "Insurance Secondary - Relationship";
    readonly 'insuranceSecondary.eligibility': "Insurance Secondary - Eligibility";
    readonly 'insuranceSecondary.status': "Insurance Secondary - Status";
    readonly 'insuranceSecondary.payerType': "Insurance Secondary - Payer Type";
    readonly 'insuranceSecondary.startDate': "Insurance Secondary - Start Date";
    readonly id: string;
    readonly assignedTo: string;
    readonly fname: string;
    readonly lname: string;
    readonly email: string;
    readonly phone: string;
    readonly dateOfBirth: string;
    readonly height: string;
    readonly weight: string;
    readonly gender: string;
    readonly tags: string;
    readonly journeys: string;
    readonly addressLineOne: string;
    readonly addressLineTwo: string;
    readonly city: string;
    readonly state: string;
    readonly zipCode: string;
    readonly landline: string;
    readonly timezone: string;
    readonly mname: string;
    readonly externalId: string;
    readonly source: string;
    readonly relationships: string;
    readonly accessTags: string;
    readonly unsubscribedFromMarketing: string;
    readonly unsubscribedFromPhones: string;
    readonly athenaDepartmentId: string;
    readonly termsVersion: string;
    readonly customTypeId: string;
};
export declare const READONLY_ENDUSER_FIELDS_TO_DISPLAY_NAME: {
    recentFormSubmittedAt: string;
    recentEventBookedAt: string;
    recentOutboundCallAt: string;
    recentInboundCallAt: string;
    recentOutboundChatAt: string;
    recentInboundChatAt: string;
    recentOutboundSMSAt: string;
    recentInboundSMSAt: string;
    recentOutboundEmailAt: string;
    recentInboundEmailAt: string;
};
export declare const ENDUSER_FIELD_TYPES: {
    email: FormFieldType[];
    phone: FormFieldType[];
    fname: FormFieldType[];
    lname: FormFieldType[];
    dateOfBirth: FormFieldType[];
    height: FormFieldType[];
    weight: FormFieldType[];
    Insurance: FormFieldType[];
};
export declare const PRIMARY_HEX = "#1564bf";
export declare const SECONDARY_HEX = "#1c4378";
export declare const ERROR_HEX = "#bf2c15";
export declare const WARNING_HEX = "#bfab15";
export declare const ADMIN_ROLE = "Admin";
export declare const BUSINESS_TYPE = "Business";
export declare const CREATOR_ONLY_ACCESS = "creatorOnly";
export declare const DEFAULT_OPERATIONS: {
    [K in Operation]: {
        title?: string;
        description?: string;
        sideEffects?: [];
    };
};
export declare const ACCESS_ACTION_FOR_OPERATION: {
    [K in Operation]: AccessAction;
};
export declare const PLACEHOLDER_ID = "60398bb15da8abef87ef41f5";
export declare const USER_SESSION_TYPE = "user";
export declare const ENDUSER_SESSION_TYPE = "enduser";
export declare const SECONDS_IN_ONE_YEAR = 31560000;
export declare const UNSEARCHABLE_FIELDS: string[];
export declare const QUESTION_GROUP_VALUE_PLACEHOLDER = "_question_group";
export declare const MM_DD_YYYY_REGEX: RegExp;
export declare const GOOGLE_INTEGRATIONS_TITLE = "Google";
export declare const PAGER_DUTY_TITLE = "Pager Duty";
export declare const SMART_METER_TITLE = "Smart Meter";
export declare const DR_CHRONO_INTEGRATIONS_TITLE = "Dr. Chrono";
export declare const DR_CHRONO_REDIRECT_URI_ENDING = "/dr-chrono-oauth2-verify";
export declare const SQUARE_INTEGRATIONS_TITLE = "Square";
export declare const SQUARE_REDIRECT_URI_ENDING = "/square-oauth2-verify";
export declare const DIALPAD_INTEGRATIONS_TITLE = "DialPad";
export declare const DIALPAD_REDIRECT_URI_ENDING = "/dialpad-oauth2-verify";
export declare const OUTLOOK_INTEGRATIONS_TITLE = "Outlook";
export declare const MICROSOFT_INTEGRATIONS_TITLE = "Microsoft";
export declare const OUTLOOK_REDIRECT_URI_ENDING = "/outlook-oauth2-verify";
export declare const MICROSOFT_OIDC_URI_ENDING = "/microsoft-oidc-verify";
export declare const OKTA_OIDC_URI_ENDING = "/okta-oidc-verify";
export declare const ZOHO_TITLE = "Zoho";
export declare const ZOHO_URI_ENDING = "/zoho-oauth2-verify";
export declare const ZOOM_TITLE = "Zoom";
export declare const ZOOM_URI_ENDING = "/zoom-oauth2-verify";
export declare const OPENAI_TITLE = "OpenAI";
export declare const HEALTHIE_TITLE = "Healthie";
export declare const ITERABLE_TITLE = "Iterable";
export declare const MEDPLUM_TITLE = "Medplum";
export declare const PHASE_ZERO_TITLE = "Phase Zero";
export declare const PHOTON_TITLE = "Photon Health";
export declare const VITAL_TITLE = "Vital";
export declare const ELATION_TITLE = "Elation";
export declare const ZUS_TITLE = "Zus";
export declare const OPEN_LOOP_TITLE = "OpenLoop";
export declare const CANVAS_TITLE = "Canvas";
export declare const MFAX_TITLE = "mFax";
export declare const CANDID_TITLE = "Candid";
export declare const GOGO_MEDS_TITLE = "GoGoMeds";
export declare const ATHENA_TITLE = "athenahealth";
export declare const SUPERDIAL_TITLE = "SuperDial";
export declare const DOSESPOT_TITLE = "DoseSpot";
export declare const DOCSUMO_TITLE = "Docsumo";
export declare const ACTIVE_CAMPAIGN_TITLE = "ActiveCampaign";
export declare const ZENDESK_INTEGRATIONS_TITLE = "Zendesk";
export declare const ZENDESK_REDIRECT_URI_ENDING = "/zendesk-oauth2-verify";
export declare const FULLSCRIPT_INTEGRATIONS_TITLE = "Fullscript";
export declare const FULLSCRIPT_REDIRECT_URI_ENDING = "/fullscript-oauth2-verify";
export declare const STRIPE_TITLE = "Stripe";
export declare const EMOTII_TITLE = "Emotii";
export declare const DEVELOP_HEALTH_TITLE = "Develop Health";
export declare const KENDRA_TITLE = "Kendra";
export declare const CHARGEBEE_TITLE = "Chargebee";
export declare const CUSTOMER_IO_TITLE = "Customer IO";
export declare const PUPPETEER_TITLE = "Puppeteer";
export declare const BELUGA_TITLE = "Beluga";
export declare const METRIPORT_TITLE = "Metriport";
export declare const PAUBOX_TITLE = "Paubox";
export declare const GENERIC_INTEGRATIONS: string[];
export declare const ORGANIZATION_WIDE_INTEGRATIONS: string[];
export declare const ONE_MINUTE_IN_MS: number;
export declare const ONE_HOUR_IN_MS: number;
export declare const ONE_DAY_IN_MS: number;
export declare const ONE_WEEK_IN_MS: number;
export declare const EMAIL_SYNC_FREQUENCY_IN_MS: number;
export declare const UNIQUENESS_VIOLATION = "Uniqueness Violation";
export declare const ALL_ACCESS: AccessType;
export declare const ASSIGNED_ACCESS: AccessType;
export declare const DEFAULT_ACCESS: AccessType;
export declare const NO_ACCESS: AccessType;
export declare const FULL_ACCESS: AccessForResource;
export declare const ASSIGNED_AND_DEFAULT_ACCESS: AccessForResource;
export declare const ASSIGNED_AND_DEFAULT_ACCESS_ALL_CREATE: AccessForResource;
export declare const DEFAULT_ONLY_ACCESS: AccessForResource;
export declare const INACCESSIBLE: AccessForResource;
export declare const READ_ONLY_ALL: AccessForResource;
export declare const READ_ONLY_ASSIGNED: AccessForResource;
export declare const READ_ONLY_DEFAULT: AccessForResource;
export declare const PROVIDER_PERMISSIONS: AccessPermissions;
export declare const ADMIN_PERMISSIONS: AccessPermissions;
export declare const PORTAL_DEFAULT_LANDING_TITLE = "Your Portal";
export declare const PORTAL_DEFAULT_LOGIN_TITLE = "Welcome back!";
export declare const PORTAL_DEFAULT_LOGIN_DESCRIPTION = "Log in to your account.";
export declare const PORTAL_DEFAULT_REGISTER_TITLE = "Getting Started";
export declare const PORTAL_DEFAULT_REGISTER_DESCRIPTION = "Let's create your account.";
export declare const CPT_CODES: {
    code: string;
    label: string;
}[];
export declare const HELPDESK_TICKET_CLOSE_REASONS: string[];
export declare const AUTOMATED_ACTION_CANCEL_REASONS: readonly ["Removed by User", "Restarted in Journey", "Form Submission", "Incoming Communication", "Removed by Automation"];
export declare const RELATIONSHIP_TYPES: ("Parent" | "Child" | "Spouse" | "Partner" | "Sibling" | "Grandparent" | "Grandchild" | "Caregiver" | "Care Recipient" | "Power of Attorney" | "Power of Attorney For" | "Emergency Contact" | "Emergency Contact For" | "Care Partner" | "Relates To" | "Referring Provider" | "Referred Patient")[];
export declare const get_inverse_relationship_type: (type: EnduserRelationship['type']) => EnduserRelationship['type'];
export declare const INSURANCE_RELATIONSHIPS_TO_CODE: {
    [K in InsuranceRelationship]: number | string;
};
export declare const INSURANCE_RELATIONSHIPS: InsuranceRelationship[];
export declare const INSURANCE_RELATIONSHIPS_ALPHABETICAL: InsuranceRelationship[];
export declare const INSURANCE_RELATIONSHIPS_CANVAS_MAPPING: {
    [K in InsuranceRelationship]?: string;
};
export declare const INSURANCE_RELATIONSHIPS_CANVAS: InsuranceRelationship[];
export declare const TELLESCOPE_GENDERS: TellescopeGender[];
export declare const VITAL_RANGE_CLASSIFICATIONS: string[];
export declare const VITAL_UNITS_INFO: Record<string, {
    label: string;
}>;
export declare const VITAL_UNITS: string[];
export declare const WEIGHT_UNITS: string[];
export declare const CANDID_MODIFIERS: string[];
export declare const DAYS_OF_WEEK_STARTING_SUNDAY: string[];
export declare const CURRENT_POLICY_VERION = "v2.0";
export declare const BUILT_INS_FOR_SET_FIELDS: (keyof Enduser)[];
export declare const BUILT_IN_BOOLEANS_FOR_SET_FIELDS: (keyof Enduser)[];
export declare const DOCUMENT_REFERENCE_CODINGS: {
    system: string;
    code: string;
}[];
export declare const DOCUMENT_TYPE_CODINGS: {
    system: string;
    code: string;
    display: string;
}[];
export declare const PORTAL_PAGES_HIDDEN_BY_DEFAULT: string[];
export declare const USER_PERSONAL_EMAIL_OVERRIDE = "personal@tellescope.com";
export declare const TELLESCOPE_PORTAL_SOURCE = "Tellescope Portal";
export type AthenaDocumentType = ("admin" | "clinicaldocument" | "imagingresult" | "labresult" | "medicalrecord" | "phonemessage" | "physicianauth");
export declare const ATHENA_DOCUMENT_TYPES_TO_DISPLAY: {
    [key in AthenaDocumentType]: {
        display: string;
        subclasses: string[];
        sources: string[];
    };
};
//# sourceMappingURL=constants.d.ts.map